### ISSUE TITLE
Issue with Docker

### ISSUE THREAD

**Issue by EceChaik** [bitcraze/toolbelt#2]
Hi guys, 

I have installed docker on my system and I'm setting the alias as said in the instructions, but it does not seem to work.
I am attaching a copy of what running the " docker run --rm -it bitcraze/toolbelt " command outputs, as well as my alias list where you can see the " tb " alias
Thank you.

$ docker run --rm -it bitcraze/toolbelt
Warning: It seems as your alias is not set up correctly. Try to run with help
Usage:  tb [-d] tool [arguments]
The toolbelt is used to develop, test and build Bitcraze modules. When the toolbelt is called, it will first try to find the tool in the belt, after that it will try the tools in the module if the working directory is the root of a module. Module tools are executed in the context of a docker container based on the module requirements configured in the module.json config file.

-d:  print the docker call that executes the tool

Tools in the belt:
  help, -h, --help - Help
  update - Update tool belt to latest version
  version, -V, --version - Display version of the tool belt
  ghrn - Generate release notes from github milestone
  docs - Serve docs locally

Tools in the current module:

Installation on linux, OSX and Windows:
Add "alias tb='docker run --rm -it -e "HOST_CW_DIR=${PWD}" -e "CALLING_HOST_NAME=$(hostname)" -e "CALLING_UID"=$UID -e "CALLING_OS"=$(uname) -v ${PWD}:/tb-module -v ${HOME}/.ssh:/root/.ssh -v /var/run/docker.sock:/var/run/docker.sock bitcraze/toolbelt'" to your .profile or .bashrc

$ alias
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias tb='docker run --rm -it -e "HOST_CW_DIR=${PWD}" -e "CALLING_HOST_NAME=$(hostname)" -e "CALLING_UID"=$UID -e "CALLING_OS"=$(uname) -v ${PWD}:/tb-module -v ${HOME}/.ssh:/root/.ssh -v /var/run/docker.sock:/var/run/docker.sock bitcraze/toolbelt'

**Comment by krichardsson** [comment]
Hi!

What happens when you run 
```tb```

**Comment by EceChaik** [comment]
$ tb

Usage:  tb [-d] tool [arguments]
The toolbelt is used to develop, test and build Bitcraze modules. When the toolbelt is called, it will first try to find the tool in the belt, after that it will try the tools in the module if the working directory is the root of a module. Module tools are executed in the context of a docker container based on the module requirements configured in the module.json config file.

-d:  print the docker call that executes the tool

Tools in the belt:
  help, -h, --help - Help
  update - Update tool belt to latest version
  version, -V, --version - Display version of the tool belt
  ghrn - Generate release notes from github milestone
  docs - Serve docs locally

Tools in the current module:

**Comment by krichardsson** [comment]
Great, looks like it works!

If you cd to one of the bitcraze repos, for instance the crazyflie-firmware repo, you will get some more tools that are implemented in that repo.

If I run the toolbelt in in my crazyflie-firmware dir I get
```
MacBook-Pro:crazyflie-firmware kristoffer$ tb
The Bitcraze internal toolbelt
Usage:  tb [-d] tool [arguments]
The toolbelt is used to develop, build and release Bitcraze modules. The toolbelt has a few tools that manipulate modules on a higher level, for instance release, but it is also used to run tools in a module. When the toolbelt is called, it will first try to find the tool in the belt, after that it will try the tools in the module, if the working directory is the root of a module. Module tools are executed in the context of a docker container, if that is configured in the module.json config file.

-d:  print the docker call that executes the tool

Tools in the belt:
  help, -h, --help - Help
  update - Update tool belt to latest version
  version, -V, --version - Display version of the tool belt
  ghrn - Generate release notes from github milestone
  docs - Serve docs locally
  release - Release a module
  dbfb - Create a database container and populate from the latest backup
  datafb - Create a data container and populate from the latest backup

Tools in the current module:
  test
  clean
  compile
  make
  build
```

And kan make the project with 

```
MacBook-Pro:crazyflie-firmware kristoffer$ tb make
Running build script tools/build/make in a container based on the bitcraze/builder docker image as user root
Using default tag: latest
latest: Pulling from bitcraze/builder
Digest: sha256:f4fe1e802da8802445054e438fd0329b4a06a4b4a97564439acf4f1c70c68a0c
Status: Image is up to date for bitcraze/builder:latest
docker.io/bitcraze/builder:latest
make: Entering directory '/module'
  CLEAN_VERSION
  CC    list.o
  CC    tasks.o
  CC    queue.o
  CC    timers.o
  CC    heap_4.o
  CC    port.o
...
```
